// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/background.jpg
var resourceBackgroundJpgData []byte
var resourceBackgroundJpg = &fyne.StaticResource{
	StaticName:    "assets/background.jpg",
	StaticContent: resourceBackgroundJpgData,
}
